services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
      - --db
      - postgres
      - --db-url
      - jdbc:postgresql://${KEYCLOAK_DATABASE_HOST}/${KEYCLOAK_DATABASE_NAME}
      - --db-username
      - ${KEYCLOAK_DATABASE_USERNAME}
      - --db-password
      - ${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "8080:8080"

